theme: jekyll-theme-dinky
title: Dr Pablo Martinez Pancorbo
email: pablomartinezpancorbo@gmail.com
github_username:  pablomartinezpancorbo

show_downloads: True
google_analytics: a133550646w193419335p189010297

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
