theme: jekyll-theme-dinky
title: IS445(AOG) - Data Viz
email: jnaiman@illinois.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is the course website for IS445(AOG) in Fall 2020
baseurl: "/is445AOG_fall2020" # the subpath of your site, e.g. /blog
url: "https://uiuc-ischool-dataviz.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jnaiman
branch: master
port: 4001

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#

defaults:
  -
    scope:
      path: "lecture*.md"
    values:
      layout: "lecture.html"
