theme: jekyll-theme-dinky
title: Dr Pablo Martinez Pancorbo
email: pablomartinezpancorbo@gmail.com
github_username:  pablomartinezpancorbo

show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
