theme: jekyll-theme-dinky
title: Dr Pablo Martinez Pancorbo
email: pablomartinezpancorbo@gmail.com
github_username:  pablomartinezpancorbo

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
